# Generated by Django 5.2.12 on 2026-03-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la promotion')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('promotion_type', models.CharField(choices=[('percentage', 'Pourcentage (%)'), ('fixed', 'Montant fixe (FCFA)')], max_length=20, verbose_name='Type de promotion')),
                ('value', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Valeur')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='products.category', verbose_name='Catégories concernées')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='products.product', verbose_name='Produits concernés')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'ordering': ['-created_at'],
            },
        ),
    ]
